### PR TITLE
add soft fail as an arg

### PR DESCRIPTION
**Pull request by mikeurbanski1**
I'll update the BC-action as well after this one

### CODE REVIEW

**Comment by schosterbarak** [comment]
Build will still fail due to problem-matcher. to enable soft fail on checkov-action see the following example: https://github.com/bridgecrewio/bridgecrew-action/blob/master/entrypoint.sh

**Comment by mikelax** [comment]
It would be great if the tiny bit of remaining work for this PR could be completed in order to get this merged. 
It would help to get this action running on existing repo.

**Comment by metahertz** [comment]
Will take a look at this!

**Comment by metahertz** [comment]
Requesting further review @schosterbarak :)

**Comment by mikelax** [comment]
Is there any update on this PR? Is it complete and able to be merged to main?

**Review by JamesWoolfenden — APPROVED** [review]
LGTM

**Pull request merged**
